name: Update Image Readme

on:
    push:
        branches:
            - master
    workflow_dispatch:
    schedule:
        # Runs at 1 UTC everyday
        - cron: "* * * 1 *"

jobs:
    update-readme:
        name: Update Image README
        runs-on: ubuntu-latest
        steps:
            - uses: siddharth2016/update-readme-image@main
                with:
                    IMG_ALT: Image ALT
                    HEIGHT: auto
                    WIDTH: auto
                    ALIGN: left
